Repository Simplon-devs/coral-AI_TCP, pull requests merged in 2023-04, with the labels that each got.

#25 Added homepage close #16
  server.py
  static/js/index.js
  static/styles/index.css
  templates/index.html
  test_script.py
Labels: enhancement

#29 Fixing stylesheets filepaths closes #28
  server.py
  static/styles/layout.css
  static/styles/sign_in.css
  static/styles/sign_up.css
  static/styles/upload.css
  templates/index.html
  templates/layout.html
  templates/sign_in.html
  templates/sign_up.html
  templates/upload.html
Labels: bug

#32 Coral info pages
  server.py
  static/js/index.js
  static/styles/coral_info.css
  templates/coral_info.html
  templates/index.html
  templates/layout.html
Labels: enhancement

#68 readme with 2 new table created and annotation updated closes #47
  bdd.py
  doc/README.md
  doc/readme_db_pic/SH316H00220828.jpg
  doc/readme_db_pic/schema.jpg
  reefscapers2020_v2.pdf
Labels: documentation, enhancement

#85 Merge resolve
  bdd.py
  doc/README.md
  doc/readme_db_pic/schema.jpg
  requirements.txt
  templates/buyers_form.html
Labels: help wanted
